version: 1
loggers:
  root:
    handlers: [console, file]
    level: DEBUG
handlers:
  console:
    class: logging.StreamHandler
    formatter: my_format
    level: DEBUG
  file:
    class: logging.FileHandler
    formatter: my_format
    filename: "./log/app.log"
    level: DEBUG
formatters:
  my_format:
    (): "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(asctime)s %(levelname)s %(name)s %(funcName)s %(message)s %(filename)s %(lineno)d"
    json_ensure_ascii: false
